### ISSUE TITLE
insert_ax on bottom

### ISSUE THREAD

**Issue by ufeindt** [MickaelRigault/astrobject#10]
@MickaelRigault , I started using your insert_ax and colorbar methods for a new version of skyhist.
Could you add bottom as an option? I think the colorbar looks better if below the sky plot.

Also note that since I'm working on the skyhist method, best ask me to merge if you want to change something. My current version is rather messy right now, though.

**Comment by MickaelRigault** [comment]
Done and tested:
from astrobject.utils import mpladdon as m
from pylab import *
ax = gca()
gca().figure.show()
axb= ax.insert_ax(0.05,0.2, location="bottom")
gca().figure.canvas.draw()
