### ISSUE TITLE
MW E(B-V) from dust maps

### ISSUE THREAD

**Issue by ufeindt** [MickaelRigault/astrobject#13]
Kyle has now hosted the Schlegel maps in the sncosmo data folders, see https://github.com/sncosmo/sncosmo/issues/129

@MickaelRigault, I can add methods to calculate extinction automatically if you remind me where you wanted them.

**Comment by MickaelRigault** [comment]
Hi Uli,

Yes I saw that, I am following sncosmo.

Look in astrobject/astrobject/baseobject.

the astrotarget have a def mwebmv

Either you put that here and we remove the setter, or you use the setter to
load it by default.

I think we should keep the setter to allow a force_mwebmv. In that case use:

"def _update_mwebmv_"

that for know do nothing.
and in "def define" move the force_mwebmv after the _update_ and set it
only if force_mwebmv is not None.

Let me know what you think is best and I let you play use that.

**Comment by ufeindt** [comment]
Alright, I started a 'dust' branch in my fork but transient_generator.get_transients() is now very (and I mean very) slow.
The extinction should preferably not be fetched on a target basis:
On my PC sncosmo.SFD98Map needs ~300 ms for a single pair of RA, Dec but and ~500 ms for 10000 coordinates, so the transient generator should fetch the values for arrays of RA and Dec.

What do you think? Should the extinction values be saved in the transient_generator? At half a second per call this seems to be worth it.
I started implementing this (not yet commited) but I got lost due all the different kinds of properties the generator has.

**Comment by MickaelRigault** [comment]
I do agree. you should look for mw_ebmv the first time you call it if it is
not already defined.
so you keep force_mwebmv such that target never call the map because it
already has something. You should however set back mw_ebmv to None in
target if you change the target coords.

The generator should indeed know the map and parse it to the targets at the
end.

**Comment by MickaelRigault** [comment]
That is great Uli, thanks, you should pull too, I've made  major updates
about catalogues and astrometry that might be useful. I'll do a report soon

**Comment by MickaelRigault** [comment]
no I thinks instead I'll do something close to what SNcosmo is doing, you
dl them the first time you need them.

**Comment by ufeindt** [comment]
Sure, ultimately we could do that, though that probably should be suggested for sncosmo.

**Comment by MickaelRigault** [comment]
Hi Uli, here is a nice ipython notebook that illustrate well the dust
extinction in the MW

https://github.com/MickaelRigault/astrobject/blob/master/notebooks/transient_generator_with_dustmap.ipynb
