### ISSUE TITLE
dust map cannot be opened

### ISSUE THREAD

**Issue by MickaelRigault** [MickaelRigault/astrobject#15]
Hi Uli, the dust fits maps seems corrupted:
In [61]: pf.open('SFD_mask_4096_sgp.fits')
ERROR: IOError: Header missing END card. [pyfits.header]

This is the same for all the 4 .fits files

**Comment by ufeindt** [comment]
pf is pyfits, I assume? If so, it works for me. Have you tried re-downloading the files?

Here are the md5sums that I get:
6f3a89528bba7d1b7bd55838da86b639  SFD_dust_4096_ngp.fits
60f7c43d51bccaff82961de3e9f9e789  SFD_dust_4096_sgp.fits
05d71e4b7c1d3f387c66096668b4db73  SFD_mask_4096_ngp.fits
0f4b2b599b03b56ac26e89676335edf3  SFD_mask_4096_sgp.fits

If that also fails, you may have to ask Kyle about the files.

**Comment by MickaelRigault** [comment]
can you send them to me ?

**Comment by MickaelRigault** [comment]
or maybe we should add them to a utils/data because it is mw dust map; it
is always useful

**Comment by ufeindt** [comment]
The files are about 150 MB in total, I don't think they should be downloaded when just cloning the repo.
I could upload them to my Dropbox but I don't understand why you can't download them from the links Kyle posted.

**Comment by MickaelRigault** [comment]
I did that, it works now, thanks

**Comment by MickaelRigault** [comment]
Hi Uli, I have slightly changed the sfd98_dir methods that now has a default one. 
I have added that, if nothing is set (so if sfd98_dir is None) than set a path where the files should be.
This directory is defined in the new utils "utils/io.py" and the data should be in utils/data/dustmap. 

Now, if nothing exists their, python will automatically dl them from sncosmo's io. (the automatic dl can be set to false). Eventually, sncosmo should do that, but in the meantime we have our technique.

I do not know where you putted your dust map dir, if you thinks utils/data/dustmap is not a good choice, we can change it.

Cheers,

**Comment by ufeindt** [comment]
The reason I set the default value of sfd98_dir to None was that in that case sncosmo looks at ~/.astropy/config/sncosmo.cfg to find out what the user set as their sfd98_dir (in my case ~/data/sfd98/).

Automatic downloading is of course a good solution but, in the long run, the files should not be placed in the package directory. That behaviour will break as soon as we make astrobject a properly installable package and someone installs it globally on there machine (as I will do on a server here at some point). Then the user wouldn't have permissions to place the files there. Instead the download folder should probably be in the user home directory (as for sncosmo models). For now we can leave it like this until this is done in sncosmo.

**Comment by MickaelRigault** [comment]
Hi Uli, You are right. I did not  know the sncosmo stuff. So maybe  should
just give a message to ask the user to set that.
I'll create an issue for kyle about te automatic downloading.

**Comment by MickaelRigault** [comment]
Done. See https://github.com/MickaelRigault/astrobject/issues/16
