### ISSUE TITLE
SurveyPlan object and lightcurve simulation

### ISSUE THREAD

**Issue by ufeindt** [MickaelRigault/astrobject#18]
Hi Mickael,

Now that we have a basic way of determining whether a transient is in a field, I suggest to add a SurveyPlan object that contains fields and observation times. It should have a method like

plan.observed_on(ra, dec)

that returns the MJDs on which a transient at those coordinates was observed. This can then be fed to the light curve generator for each SN.

Does this sound good to you? I'll get started on a basic version.

NB: Some things about the fields may have to be redone later depending on what the input will look like but that shouldn't keep us from setting up the internal structure.

**Comment by MickaelRigault** [comment]
This sounds goods.
SurveyPlan should have a "cadence" property which I think should be a dict
(or astropy Table) that have mdj, ra, dec, band

I let you start that. I am working on the Several-objsevation Containers
("Collection") that create SED or lightcurve Object. Almost ready.

Cheers,
