### ISSUE TITLE
Run Test with PTF data

### ISSUE THREAD

**Issue by MickaelRigault** [MickaelRigault/astrobject#30]
Hi Uli, 

If you pull, the ptf data should be able to do all what the sdss data do in the notebook examples. 
Could you test that ? Notably the photomap trick.

**Comment by ufeindt** [comment]
Done. I ran PhotoPointCollection__PhotoMap.ipynb (you meant that one right?) on one of the M82 fields and one from the clear field. No error messages but a lot of warnings that an SDSS equivalent band was used when running get_photopoints() but I assume that what one expects.

I'm attaching the Voronoi tessellation plots for both field. The clear field looks nice but something's not right with M82.
![cf_voronoi](https://cloud.githubusercontent.com/assets/9607945/13684669/0b21e738-e70d-11e5-9b05-5b724d1e3d4c.png)
![m82_voronoi](https://cloud.githubusercontent.com/assets/9607945/13684670/0b26bf56-e70d-11e5-92b7-3e8481c68cac.png)

**Comment by MickaelRigault** [comment]
Hi uli, I've tried to and have a normal Voronoy image in both cases. Could
you let me know the field you used ?

**Comment by ufeindt** [comment]
The first R-band file in both cases, for M82 the filename is 
M82_R_2009-03-17_03-40-51.878000.fits

Which file did you use?

On 2016-03-11 22:41, Mickael Rigault wrote:

> Hi uli, I've tried to and have a normal Voronoy image in both cases. Could
> you let me know the field you used ?
> 
> On Thu, Mar 10, 2016 at 10:23 PM, Ulrich Feindt notifications@github.com
> wrote:
> 
> > Done. I ran PhotoPointCollection__PhotoMap.ipynb (you meant that one
> > right?) on one of the M82 fields and one from the clear field. No error
> > messages but a lot of warnings that an SDSS equivalent band was used 
> > when
> > running get_photopoints() but I assume that what one expects.
> > 
> > I'm attaching the Voronoi tessellation plots for both field. The clear
> > field looks nice but something not right with M82.
> > [image: cf_voronoi]
> > 
> > https://cloud.githubusercontent.com/assets/9607945/13684669/0b21e738-e70d-11e5-9b05-5b724d1e3d4c.png
> > [image: m82_voronoi]
> > 
> > https://cloud.githubusercontent.com/assets/9607945/13684670/0b26bf56-e70d-11e5-92b7-3e8481c68cac.png
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/MickaelRigault/astrobject/issues/30#issuecomment-195055541
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MickaelRigault/astrobject/issues/30#issuecomment-195565632.

## 

Ulrich Feindt
Oskar Klein Centre for Cosmoparticle Physics
Department of Physics, Stockholm University
AlbaNova University Center, SE-106 91 Stockholm, SWEDEN
tel: +46 8 55378035

**Comment by MickaelRigault** [comment]
Arf, I only have the 2011 files...

**Comment by MickaelRigault** [comment]
and 2012

**Comment by MickaelRigault** [comment]
oups sorry (tired) all years after 2010

**Comment by ufeindt** [comment]
So you're missing 2009 and 2010? Weird, these were the first ones I uploaded to the cc.
How many files do you have? If you give me a file filelist (per email) I can upload the missing ones.
In the meantime, which image did you try it on?

**Comment by MickaelRigault** [comment]
I've tried any other file and it works. I'm about to pull with a major
update on catalogue methods and astropy/astLib wcs conflict. You should not
see the difference. The catalog update should enable to easily do the local
photometry. I still have to think about it, but I think local photometry
should be an photomap method. What do you think ?

Cheers,

**Comment by ufeindt** [comment]
I have tried the first three of the 2012 R-band M82 image and get the same weird plot. Do I have to change something in the notebook except the filename?

Regarding local photometry: I probably don't know the structure of the code well enough but photomap sounds like the right place.

**Comment by MickaelRigault** [comment]
haa... looks like nan issue in the colorbars, but only in notebook !!

**Comment by MickaelRigault** [comment]
Fixed.

Could you pull and test

nan colors are now transparent and inf value goes to max

**Comment by MickaelRigault** [comment]
[image: Inline image 1]

**Comment by ufeindt** [comment]
It works now.
![m82_voronoi](https://cloud.githubusercontent.com/assets/9607945/13731884/d7043ebe-e974-11e5-9a60-36ac10f1e2ea.png)
