### ISSUE TITLE
mjd_obstime access error

### ISSUE THREAD

**Issue by vbrinnel** [MickaelRigault/astrobject#31]
On ccage.in2p3.fr:

import astrobject as ao
sdssg = ao.instrument("/sps/snovae/user/rigault/Data/SDSS/FRAMES/frame-g-000752-3-0674.fits.gz")
sdssg.mjd_obstime

ValueError                                Traceback (most recent call last)
/sps/snovae/user/vbrinnel/HostCosmology/<ipython-input-64-6d7a597fecf6> in <module>()
----> 1 sdssg.mjd_obstime

/sps/snovae/user/vbrinnel/HostCosmology/gitlab/astrobject/astrobject/instruments/sdss.pyc in mjd_obstime(self)
    174             raise AttributeError("no header loaded ")
    175         from astropy import time
--> 176         return time.Time("%sT%s"%(self.header["DATE-OBS"],self.header["TAIHMS"])).mjd
    177 
    178     # -- Derived values

/usr/local/python/python-2.7/lib/python2.7/site-packages/astropy/time/core.pyc in **init**(self, val, val2, format, scale, precision, in_subfmt, out_subfmt, location, copy)
    196                 self._set_scale(scale)
    197         else:
--> 198             self._init_from_vals(val, val2, format, scale, copy)
    199 
    200         if self.location:

/usr/local/python/python-2.7/lib/python2.7/site-packages/astropy/time/core.pyc in _init_from_vals(self, val, val2, format, scale, copy)
    238 
    239         # Parse / convert input values into internal jd1, jd2 based on format

--> 240         self._time = self._get_time_fmt(val, val2, format, scale)
    241         self._format = self._time.name
    242 

/usr/local/python/python-2.7/lib/python2.7/site-packages/astropy/time/core.pyc in _get_time_fmt(self, val, val2, format, scale)
    276                 pass
    277         else:
--> 278             raise ValueError('Input values did not match {0}'.format(err_msg))
    279 
    280     @classmethod

ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']

**Comment by MickaelRigault** [comment]
The issue comes from the SDSS header that is not consistant:

first case works, the second do not
sdssg.header["DATE-OBS"],sdssg.header["TAIHMS"]
Out[31]: ('2009-01-29', '05:09:39.39')

In [32]: sdss.header["DATE-OBS"],sdss.header["TAIHMS"]
Out[32]: ('21/03/99', '11:29:53.55')

I am implementing a work around

**Comment by MickaelRigault** [comment]
Fixed and tested
Work around:
dateobs = self.header["DATE-OBS"] if "/" not in self.header["DATE-OBS"]\
          else "19"+"-".join(self.header["DATE-OBS"].split("/")[::-1])

return time.Time("%sT%s"%(dateobs,self.header["TAIHMS"])).mjd
