### ISSUE TITLE
sky display

### ISSUE THREAD

**Issue by MickaelRigault** [MickaelRigault/astrobject#4]
We should have a function to easily display the target in the sky, like Uli's plot.
IMHO, we should have a  function in the utils/mlpaddon.py to create a axes/figure add-on and then use it in simultransient.py "TransientGenerator". I've created the two modules show and display. The former shall enable to plot it directly while the latter enable to draw the points in any given ax. In my experience this is more than useful. 
There is example e.g. in photometry.py

**Comment by ufeindt** [comment]
I'm looking into and might come back to you with some questions regarding making the add-ons.
Right now, I'm using the basemap package for the sky plot, which does not install cleanly through, so usually install it manually. It might be possible to do the same using basic matplotlib but I have yet to figure that out.
I put an example of using basemap here:  https://gist.github.com/ufeindt/187f2ddd0a89d3d9fb68
Not sure what the best way to go is, since manipulating the plot requires keeping the Basemap object.

**Comment by MickaelRigault** [comment]
ok, I do not have basemap natively, so that might not be so great.

This looks nice to:
http://scitools.org.uk/cartopy/docs/latest/gallery.html

**Comment by ufeindt** [comment]
Yeah, as I said, I also need to install it manually.

Cartopy does look nice, but I can't seem to install it using pip and there is no apt-get package for it. Also it has a lot of dependencies. I'll see if I can make it work but if it is also a struggle, it might not be the best option either.

**Comment by MickaelRigault** [comment]
Yeah I saw.

We should look for an easy technique. I'll let you manage that.

Cheers

**Comment by ufeindt** [comment]
Alright, I'll think about. Maybe I can make a version that only uses the built-in matplotlib stuff but is rather limited (and tells you to use Basemap or Cartopy if you try certain things). This may mean that you can't easily change the RA around which the plot is centered (which isn't too bad) and maybe not use celestial mappings (RA goes the other way than terrestrial longitude, which would be annoying).

Maybe I'll make a basic version and a more sophisticated one that requires basemap.

**Comment by MickaelRigault** [comment]
Hi Uli, 

I've did an some run on transient generator to start working of the simulation. There is a tiny bug in the skyplot:

> > t = st.transient_generator(1000,zrange=[0.01,0.1])
> > t.show_skycoverage()
> > I have the RA[deg] label in the middle of the plot.
> > ![bug_skyplot](https://cloud.githubusercontent.com/assets/7812822/11766462/7e889a7e-a189-11e5-9d73-f82e0ffd1db7.png)

Cheers,

**Comment by ufeindt** [comment]
Yeah, I had the same when I run it on my laptop but not on my office desktop. Which matplotlib version are you using? This might be a bug in there.

On 13 December 2015 11:06:59 CET, Mickael Rigault notifications@github.com wrote:

> Hi Uli, 
> 
> I've did an some run on transient generator to start working of the
> simulation. There is a tiny bug in the skyplot:
> 
> > > t = st.transient_generator(1000,zrange=[0.01,0.1])
> > > t.show_skycoverage()
> > > I have the RA[deg] label in the middle of the plot.
> > > ![bug_skyplot](https://cloud.githubusercontent.com/assets/7812822/11766462/7e889a7e-a189-11e5-9d73-f82e0ffd1db7.png)
> 
> Cheers,
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MickaelRigault/astrobject/issues/4#issuecomment-164243905

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MickaelRigault** [comment]
I'll check.

Note that I am reformating the simul package including a RateGenerator, so
no more npoints to set we should still be able to do so) but a
ratefunction. I'll let you know when this is ready
