### ISSUE TITLE
syntax error on import in galex.py

### ISSUE THREAD

**Issue by rrgupta** [MickaelRigault/astrobject#68]
Hi Mickael,

I am getting an error when I import the newest version of astrobject. The error is in
../astrobject/instruments/galex.py", line 259
```
    self._properties['bandname'] "fuv" if "-fd-" in self.filename else "nuv" if "-nd-" in self.filename \
                                     ^
SyntaxError: invalid syntax
```
I think maybe you are just missing an "=" sign?
Thanks,
Ravi

**Comment by MickaelRigault** [comment]
Merged so closed. 
Thanks for the fix
