### ISSUE TITLE
sky area in degree2

### ISSUE THREAD

**Issue by MickaelRigault** [MickaelRigault/astrobject#7]
Hi Uli, 

for sncosmo, we need to have the sky area covered by our simulation. 
Can you do that ?  It will need the same input parameters as random.radec but return the covered area in degree^2.

I guess astropy might already have function close to that

**Comment by ufeindt** [comment]
Sure, if it is just a rectangle, it is very easy: https://en.wikipedia.org/wiki/Solid_angle#Latitude-longitude_rectangle

**Comment by MickaelRigault** [comment]
yep but you also have the avoid_mw area.

I'll let you handle that and we can close our first issue !!

**Comment by ufeindt** [comment]
Right, that is a bigger problem. I don't think this has been done somewhere. I should be able figure this out but do we really need it? Won't we eventually move to covering the sky with observation fields and leave out places those at high MW extinction?
