### ISSUE TITLE
'lbda' AttributeError for newly added instruments

### ISSUE THREAD

**Issue by rrgupta** [MickaelRigault/astrobject#70]
Hi Mickael,
I'm trying to add 2MASS as a new instrument and was running some tests. I created a twomass.py instrument file very similar to the one I created for WISE (and modeled after your existing files) but for both 2MASS and WISE I am getting the following error from `photometry.pyc` when doing `get_target_photopoint()`:
`AttributeError: 'PhotoPoint' object has no attribute 'lbda'`
My instrument files contain *_INFO at the top which defines `'lbda'` for each filter, and also I have loaded the appropriate passbands into sncosmo (with the same bandname) for both 2MASS and WISE. Do you know what I am missing and why `'lbda'` is not being recognized? I want to make sure my wise.py and twomass.py files are OK before pushing them and issuing a PR.

Thanks,
Ravi

**Comment by MickaelRigault** [comment]
Hi Ravi, 

Thanks for that. It was actually my fault. 

I've removed the lbda from `PhotoPoint` thinking I was removing it from `Image`.
I've changed that back. 
However `bandpass` is not anymore part of `PhotoPoint` (instruments have it) as I do not think it should. Let me know if that is an issue for you. 

get the latest version (0.5.6) this is fixed.

Cheers,
Mickael
