### ISSUE TITLE
astrometry.photometry.image should have method zoom()

### ISSUE THREAD

**Issue by rgraz** [MickaelRigault/astrobject#73]
Does astrometry.photometry.image should have a method named zoom() or whatever the name with argument xmin,xmax,ymin,ymax and returns an updated (or do it inplace)  instance of Image with the new image zoomed on xmin,xmax,ymin,ymax ?

**Comment by MickaelRigault** [comment]
there now is a 
Image.get_subimage(xmin,xmax, ymin, ymax). No inplace so far, only returns a new object.
